In [100]:
import numpy as np

In [101]:
# Action 🎬

def softmax(vector):
    e = np.exp(vector)
    return e / e.sum()
    
def linear(vector):
    
    """
    We need to calculate WTx + b 
    But our vector is ,indeed, the same
    
    Nevermind, you'll understand later 
    
    """
    return vector


class FirstNeuralNework:
    # Hey, sailor! Welcome aboard, we are always glad to new friends.
    # Always follow Captain's orders. 
    # Remember, our goal is to find a treasure map. 💎 🗺️
    
    def __init__(self, layers_vector, outputs_type):
        
        if outputs_type.upper() == "PROBABILITY":
            self.activation_way = softmax
        else:
            self.activation_way = linear   
        """
        Some information about
        
        layers_vector -- [0] --> number of input neurons
                      -- [1:-1]  --> lenght of each layer
                      -- [-1] --> number of output neurons              
        
         Setting random weights 
         weights[-1] --> bias
         
         """
        
        self.layers_vector = layers_vector
        self.weights = []
        for i in range(1, len(self.layers_vector) - 1):
            # Setting weights at (-1:1)
            w = 2 * np.random.random((self.layers_vector[i-1], self.layers_vector[i] + 1)) - 1
            # Adding one here <self.layers_vector[i-1] + 1> cause of bias 
            
            self.weights.append(w)
            
        w = 2 * np.random.random((self.layers_vector[i], layers_vector[i + 1] + 1)) -1
        self.weights.append(w)                        
        # Now we have the First clue to the pirate treasure map.🗝
    
    def summing(self, x, index):
        print(self.weights[index])
        return np.dot(x.T, self.weights[index])
    
    
    def sigmoid(self, addition):
        print(addition)
        return 1 / (1 + np.e ** (-addition))
    
    
    def feed_forward(self, x): 
        
        """
        X-INPUT --> vector or matrix
        
        Now we are going to push forward our model
        
        Adding ones at the end for bias
        If x is 1d np.hstack will return an error
        """ 
        
        try:
            n = np.array(x).shape[0]
            ones_column = np.ones((n,1))
            x = np.hstack((x, ones_column))
            print(x)
        except ValueError:
            x += [1]
        
        dont_forget = dict()
        n = x.shape[0]
        act = x
        for index in range(len(self.layers_vector) - 1):
            print(index)
            preact = self.summing(act[:n], index)
            act = self.sigmoid(preact)
            dont_forget["Preactivation" + str(index + 1)] = preact
            dont_forget["Activation" + str(index + 1)] = act
         
        preact = self.summing(np.transpose(act), index)
        act = self.activation_way(preact)
        dont_forget["Preactivation" + str(index + 1)] = preact
        dont_forget["Activation" + str(index + 1)] = act
        
        return act, dont_forget
    
        # Set sail! There is a Shark.🦈🏴‍☠️
    
    """

    To be continued...

    """                         

In [102]:
lay = [3,3,3,2]
test = FirstNeuralNework(lay, "Probability")
test.weights

[array([[ 0.15827445, -0.19490208, -0.58804668,  0.0919204 ],
        [ 0.5864056 ,  0.69929738,  0.48443954,  0.12202542],
        [-0.33655052,  0.77142713, -0.98224302,  0.66562357]]),
 array([[-0.22550899, -0.69893516,  0.44223119,  0.4635144 ],
        [ 0.41924637, -0.84907101,  0.44201946,  0.81895096],
        [-0.31819419, -0.93157191, -0.88291063,  0.96730709]]),
 array([[-0.18535594, -0.28874483, -0.5699457 ],
        [ 0.73566822, -0.41395986,  0.71734574],
        [ 0.92613781, -0.03210042,  0.79083046]])]

In [103]:
test.feed_forward(np.array([4,5,6]))

0
[[ 0.15827445 -0.19490208 -0.58804668  0.0919204 ]
 [ 0.5864056   0.69929738  0.48443954  0.12202542]
 [-0.33655052  0.77142713 -0.98224302  0.66562357]]
[ 1.95395221  8.62126376 -6.90929732  5.8511195 ]
1
[[-0.22550899 -0.69893516  0.44223119  0.4635144 ]
 [ 0.41924637 -0.84907101  0.44201946  0.81895096]
 [-0.31819419 -0.93157191 -0.88291063  0.96730709]]
[ 0.22133531 -1.46202841  0.82839925  1.22574982]
2
[[-0.18535594 -0.28874483 -0.5699457 ]
 [ 0.73566822 -0.41395986  0.71734574]
 [ 0.92613781 -0.03210042  0.79083046]]
[ 0.68013564 -0.26051684  0.36902275]
[[-0.18535594 -0.28874483 -0.5699457 ]
 [ 0.73566822 -0.41395986  0.71734574]
 [ 0.92613781 -0.03210042  0.79083046]]


(array([0.49243713, 0.15819807, 0.3493648 ]),
 {'Preactivation1': array([ 1.95395221,  8.62126376, -6.90929732,  5.8511195 ]),
  'Activation1': array([8.75876951e-01, 9.99819800e-01, 9.97463216e-04, 9.97131575e-01]),
  'Preactivation2': array([ 0.22133531, -1.46202841,  0.82839925,  1.22574982]),
  'Activation2': array([0.55510903, 0.18815728, 0.69601635, 0.77307383]),
  'Preactivation3': array([ 0.74471006, -0.39080887,  0.40145991]),
  'Activation3': array([0.49243713, 0.15819807, 0.3493648 ])})

In [104]:
test.feed_forward(np.array([[4,5,6],[8,5,6],[12,10,3]]))

[[ 4.  5.  6.  1.]
 [ 8.  5.  6.  1.]
 [12. 10.  3.  1.]]
0
[[ 0.15827445 -0.19490208 -0.58804668  0.0919204 ]
 [ 0.5864056   0.69929738  0.48443954  0.12202542]
 [-0.33655052  0.77142713 -0.98224302  0.66562357]]
[[  1.28573636  14.07189622 -10.26358669   9.33136778]
 [  0.35789506  10.23624777 -10.34046594   7.72596479]
 [  3.45842873   5.34065317  -3.5683719    3.28054562]
 [  0.40812953   1.27582243  -1.08585016   0.87956939]]
1
[[-0.22550899 -0.69893516  0.44223119  0.4635144 ]
 [ 0.41924637 -0.84907101  0.44201946  0.81895096]
 [-0.31819419 -0.93157191 -0.88291063  0.96730709]]
[[-0.23841328 -1.95040921 -0.24936865  1.7828928 ]
 [-0.12295391 -2.47510362  0.00553522  2.24512879]
 [-0.00872182 -0.02560315 -0.02418696  0.02657412]
 [-0.11308889 -2.44537719  0.03310669  2.21431049]]
2
[[-0.18535594 -0.28874483 -0.5699457 ]
 [ 0.73566822 -0.41395986  0.71734574]
 [ 0.92613781 -0.03210042  0.79083046]]
[[ 0.72461657 -0.33749498  0.47917917]
 [ 0.49116685 -0.08392842  0.37507219]
 [ 0.7

(array([[0.12367822, 0.03954931, 0.0871321 ],
        [0.12781457, 0.03916568, 0.09211306],
        [0.12388196, 0.03954074, 0.08706998],
        [0.11836159, 0.04008424, 0.08160854]]),
 {'Preactivation1': array([[  1.28573636,  14.07189622, -10.26358669,   9.33136778],
         [  0.35789506,  10.23624777, -10.34046594,   7.72596479],
         [  3.45842873,   5.34065317,  -3.5683719 ,   3.28054562],
         [  0.40812953,   1.27582243,  -1.08585016,   0.87956939]]),
  'Activation1': array([[7.83424650e-01, 9.99999226e-01, 3.48791414e-05, 9.99911407e-01],
         [5.88530791e-01, 9.99964154e-01, 3.22982265e-05, 9.99558974e-01],
         [9.69481512e-01, 9.95230122e-01, 2.74282085e-02, 9.63755347e-01],
         [6.00639290e-01, 7.81737822e-01, 2.52400525e-01, 7.06732980e-01]]),
  'Preactivation2': array([[-0.23841328, -1.95040921, -0.24936865,  1.7828928 ],
         [-0.12295391, -2.47510362,  0.00553522,  2.24512879],
         [-0.00872182, -0.02560315, -0.02418696,  0.02657412],
  